ALTER TABLE repository
    ADD COLUMN github_id INTEGER UNIQUE NOT NULL;

ALTER TABLE release
    ADD COLUMN github_id INTEGER UNIQUE NOT NULL;

ALTER TABLE asset
    ADD COLUMN github_id INTEGER UNIQUE NOT NULL;