ALTER TABLE repository
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE repository
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE release
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE asset
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "user"
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE "user"
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;