FROM debian:bookworm AS certs

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

FROM golang:1.24 AS builder

# define the build arguments
ARG GIT_VERSION
ARG GIT_COMMIT
ARG GIT_DATE

ENV GIT_VERSION=${GIT_VERSION}
ENV GIT_COMMIT=${GIT_COMMIT}
ENV GIT_DATE=${GIT_DATE}

# build everything
COPY . /.
RUN CGO_ENABLED=0 go build -o /peanut -ldflags="-X 'peanut/internal/buildinfo.Version=${GIT_VERSION}' -X 'peanut/internal/buildinfo.Commit=${GIT_COMMIT}' -X 'peanut/internal/buildinfo.BuildTime=${GIT_DATE}'" /.

FROM scratch

# set env to tell the binary to use absolute paths
ENV IS_CONTAINER=true

# Copy binary
COPY --from=builder /peanut /usr/bin/

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/usr/bin/peanut"]