// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID            pgtype.Int4
	Apiurl        pgtype.Text
	Url           pgtype.Text
	Name          pgtype.Text
	Contentlength pgtype.Int4
	Downloadcount pgtype.Int4
	Viewcount     pgtype.Int4
	Createdat     pgtype.Timestamp
	Updatedat     pgtype.Timestamp
	Uploadedat    pgtype.Timestamp
}

type Release struct {
	ID              int32
	Name            pgtype.Text
	Tagname         pgtype.Text
	Body            pgtype.Text
	Draft           pgtype.Bool
	Prerelease      pgtype.Bool
	Createdat       pgtype.Timestamp
	Publishedat     pgtype.Timestamp
	Authorname      pgtype.Text
	Authorid        pgtype.Text
	Authoravatarurl pgtype.Text
}

type Repository struct {
	ID        pgtype.UUID
	Owner     pgtype.Text
	Name      pgtype.Text
	Token     pgtype.Text
	Isprivate pgtype.Bool
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}

type User struct {
	ID          pgtype.UUID
	Username    pgtype.Text
	Displayname pgtype.Text
	Passhash    pgtype.Text
	Createdat   pgtype.Timestamp
	Updatedat   pgtype.Timestamp
}
