// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID            int32
	GithubID      int32
	ApiUrl        pgtype.Text
	Url           pgtype.Text
	Name          pgtype.Text
	ContentLength pgtype.Int4
	DownloadCount pgtype.Int4
	ViewCount     pgtype.Int4
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	UploadedAt    pgtype.Timestamp
	ReleaseID     pgtype.Int4
}

type Release struct {
	ID              int32
	GithubID        int32
	Name            pgtype.Text
	TagName         pgtype.Text
	Body            pgtype.Text
	IsDraft         pgtype.Bool
	IsPrerelease    pgtype.Bool
	CreatedAt       pgtype.Timestamp
	PublishedAt     pgtype.Timestamp
	AuthorName      pgtype.Text
	AuthorID        pgtype.Text
	AuthorAvatarUrl pgtype.Text
	RepositoryID    pgtype.Int4
}

type Repository struct {
	ID        int32
	GithubID  int32
	UserID    pgtype.Int4
	Owner     pgtype.Text
	Name      pgtype.Text
	Token     pgtype.Text
	IsPrivate pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID          int32
	Username    pgtype.Text
	DisplayName pgtype.Text
	PassHash    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
